export interface IeltsWord {
  word: string;
  meaning: string;
}

export const IELTS_WORDS: IeltsWord[] = [
  { word: "achieve", meaning: "to successfully reach a goal" },
  { word: "adapt", meaning: "to change to fit a new situation" },
  { word: "adequate", meaning: "enough or satisfactory for a purpose" },
  { word: "allocate", meaning: "to distribute resources for a purpose" },
  { word: "analyze", meaning: "to examine something in detail" },
  { word: "approach", meaning: "a way of dealing with something" },
  { word: "approximate", meaning: "close to the actual but not exact" },
  { word: "assess", meaning: "to evaluate or estimate something" },
  { word: "assume", meaning: "to accept something without proof" },
  { word: "attribute", meaning: "a quality or feature of something" },
  { word: "benefit", meaning: "an advantage or positive result" },
  { word: "bias", meaning: "an unfair preference for or against something" },
  { word: "capacity", meaning: "the maximum amount something can hold" },
  { word: "circumstance", meaning: "a condition connected to an event" },
  { word: "clarify", meaning: "to make something easier to understand" },
  { word: "coherent", meaning: "logical and consistent" },
  { word: "collapse", meaning: "to fall down or fail suddenly" },
  { word: "compensate", meaning: "to make up for something" },
  { word: "complex", meaning: "consisting of many connected parts" },
  { word: "component", meaning: "a part of a larger whole" },
  { word: "conceive", meaning: "to form an idea or plan in the mind" },
  { word: "concentrate", meaning: "to focus attention on something" },
  { word: "conclude", meaning: "to bring to an end or reach a decision" },
  { word: "conduct", meaning: "to carry out or organize an activity" },
  { word: "confine", meaning: "to keep within certain limits" },
  { word: "conflict", meaning: "a serious disagreement or struggle" },
  { word: "consent", meaning: "permission or agreement to do something" },
  { word: "consequently", meaning: "as a result of something" },
  { word: "considerable", meaning: "large in size, amount, or importance" },
  { word: "consist", meaning: "to be made up of certain parts" },
  { word: "constant", meaning: "happening all the time without change" },
  { word: "constitute", meaning: "to form or make up something" },
  { word: "constrain", meaning: "to limit or restrict" },
  { word: "consume", meaning: "to use up a resource" },
  { word: "contemplate", meaning: "to think about something deeply" },
  { word: "contradict", meaning: "to say the opposite of a statement" },
  { word: "contribute", meaning: "to give something to help achieve a goal" },
  { word: "controversy", meaning: "a public disagreement about something" },
  { word: "convention", meaning: "a widely accepted way of doing things" },
  { word: "convince", meaning: "to persuade someone to believe something" },
  { word: "crucial", meaning: "extremely important or necessary" },
  { word: "decline", meaning: "to decrease in amount or quality" },
  { word: "demonstrate", meaning: "to show clearly or prove something" },
  { word: "derive", meaning: "to obtain something from a source" },
  { word: "detect", meaning: "to discover or notice something" },
  { word: "deviate", meaning: "to depart from an established course" },
  { word: "diminish", meaning: "to make or become smaller or less" },
  { word: "distinct", meaning: "clearly different or separate" },
  { word: "distort", meaning: "to change the shape or truth of something" },
  { word: "diverse", meaning: "showing a great deal of variety" },
  { word: "dominant", meaning: "having the most power or influence" },
  { word: "draft", meaning: "a preliminary version of a piece of writing" },
  { word: "eliminate", meaning: "to completely remove or get rid of" },
  { word: "emphasize", meaning: "to give special importance to something" },
  { word: "encounter", meaning: "to unexpectedly meet or experience something" },
  { word: "enhance", meaning: "to improve the quality or value of something" },
  { word: "enormous", meaning: "extremely large in size or amount" },
  { word: "ensure", meaning: "to make certain that something happens" },
  { word: "establish", meaning: "to set up or create on a firm basis" },
  { word: "evaluate", meaning: "to judge the value or quality of something" },
  { word: "evident", meaning: "clearly seen or understood" },
  { word: "exceed", meaning: "to go beyond a limit or expectation" },
  { word: "exclude", meaning: "to deliberately leave out or not include" },
  { word: "exhibit", meaning: "to display or show publicly" },
  { word: "expand", meaning: "to increase in size or scope" },
  { word: "exploit", meaning: "to use something to gain an advantage" },
  { word: "facilitate", meaning: "to make a process easier" },
  { word: "fluctuate", meaning: "to rise and fall irregularly" },
  { word: "fundamental", meaning: "forming a necessary base or core" },
  { word: "generate", meaning: "to produce or create something" },
  { word: "globe", meaning: "the earth or a spherical representation of it" },
  { word: "guarantee", meaning: "a firm promise that something will happen" },
  { word: "hence", meaning: "as a consequence or for this reason" },
  { word: "hypothesis", meaning: "a proposed explanation for something" },
  { word: "identical", meaning: "exactly alike in every way" },
  { word: "ignorance", meaning: "a lack of knowledge or awareness" },
  { word: "illustrate", meaning: "to explain or make clear with examples" },
  { word: "impact", meaning: "a strong effect or influence" },
  { word: "implement", meaning: "to put a plan or decision into effect" },
  { word: "implication", meaning: "a possible effect or consequence" },
  { word: "impose", meaning: "to force something on someone" },
  { word: "incentive", meaning: "something that motivates action" },
  { word: "incidence", meaning: "the rate at which something occurs" },
  { word: "indicate", meaning: "to point out or show something" },
  { word: "inevitable", meaning: "certain to happen and unavoidable" },
  { word: "infer", meaning: "to conclude from evidence or reasoning" },
  { word: "infrastructure", meaning: "basic physical systems of a society" },
  { word: "inherent", meaning: "existing as a natural part of something" },
  { word: "inhibit", meaning: "to prevent or slow down a process" },
  { word: "initial", meaning: "existing at the beginning" },
  { word: "innovate", meaning: "to introduce new ideas or methods" },
  { word: "inspect", meaning: "to look at something carefully" },
  { word: "integral", meaning: "essential and necessary for completeness" },
  { word: "intense", meaning: "of extreme force, degree, or strength" },
  { word: "intervene", meaning: "to become involved to change an outcome" },
  { word: "isolate", meaning: "to separate from others" },
  { word: "justify", meaning: "to show something is right or reasonable" },
  { word: "maintain", meaning: "to keep in good condition over time" },
  { word: "manipulate", meaning: "to control or influence something cleverly" },
  { word: "mediate", meaning: "to help resolve a dispute between others" },
  { word: "migrate", meaning: "to move from one place to another" },
  { word: "minimize", meaning: "to reduce to the smallest possible amount" },
  { word: "modify", meaning: "to make partial changes to something" },
  { word: "monitor", meaning: "to observe and check over time" },
  { word: "mutual", meaning: "shared by two or more parties" },
  { word: "neglect", meaning: "to fail to care for something properly" },
  { word: "nonetheless", meaning: "in spite of that; nevertheless" },
  { word: "norm", meaning: "a standard that is typical or expected" },
  { word: "notion", meaning: "a general understanding or idea" },
  { word: "obtain", meaning: "to get or acquire something" },
  { word: "obvious", meaning: "easily perceived or understood" },
  { word: "occupy", meaning: "to fill or take up a space or position" },
  { word: "occur", meaning: "to happen or take place" },
  { word: "ongoing", meaning: "continuing without interruption" },
  { word: "orient", meaning: "to direct toward a particular goal" },
  { word: "outcome", meaning: "the result or consequence of an action" },
  { word: "overlap", meaning: "to extend over and cover partly" },
  { word: "perceive", meaning: "to become aware of through the senses" },
  { word: "persist", meaning: "to continue firmly despite difficulty" },
  { word: "phenomenon", meaning: "a remarkable fact or event" },
  { word: "pose", meaning: "to present or raise a question or problem" },
  { word: "precede", meaning: "to come before in time or order" },
  { word: "predominant", meaning: "present as the strongest element" },
  { word: "presume", meaning: "to suppose something is true without proof" },
  { word: "prevalent", meaning: "widespread or commonly occurring" },
  { word: "principal", meaning: "first in order of importance" },
  { word: "proceed", meaning: "to begin or continue a course of action" },
  { word: "prohibit", meaning: "to formally forbid by law or rule" },
  { word: "prospect", meaning: "the possibility of future success" },
  { word: "pursue", meaning: "to follow or chase in order to catch" },
  { word: "radical", meaning: "relating to fundamental or extreme change" },
  { word: "refine", meaning: "to improve by making small changes" },
  { word: "regime", meaning: "a system of government or management" },
  { word: "reinforce", meaning: "to strengthen or support" },
  { word: "reluctance", meaning: "unwillingness or hesitation to do something" },
  { word: "restrain", meaning: "to hold back or keep under control" },
  { word: "retain", meaning: "to continue to keep or hold" },
  { word: "revenue", meaning: "income generated from business or taxes" },
  { word: "rigid", meaning: "unable to bend or be forced out of shape" },
  { word: "simulate", meaning: "to imitate the appearance of something" },
  { word: "sole", meaning: "one and only; single" },
  { word: "somewhat", meaning: "to a moderate extent or degree" },
  { word: "submit", meaning: "to present something for consideration" },
  { word: "subordinate", meaning: "lower in rank or position" },
  { word: "subsequent", meaning: "coming after something in time" },
  { word: "subsidiary", meaning: "less important than but related to" },
  { word: "sufficient", meaning: "enough to meet a need" },
  { word: "suppress", meaning: "to forcibly put an end to something" },
  { word: "sustain", meaning: "to maintain something over a period" },
  { word: "terminate", meaning: "to bring to an end" },
  { word: "thereby", meaning: "by that means; as a result of that" },
  { word: "trace", meaning: "to find the origin of something" },
  { word: "transform", meaning: "to change completely in form or nature" },
  { word: "transmit", meaning: "to send or pass something to another" },
  { word: "trigger", meaning: "to cause an event or process to begin" },
  { word: "undergo", meaning: "to experience or be subjected to" },
  { word: "undertake", meaning: "to commit to and begin a task" },
  { word: "utilize", meaning: "to make practical use of something" },
  { word: "valid", meaning: "having a sound basis in logic or fact" },
  { word: "vary", meaning: "to differ or change from one form to another" },
  { word: "violate", meaning: "to break a rule, law, or agreement" },
  { word: "visible", meaning: "able to be seen or noticed" },
  { word: "widespread", meaning: "found or distributed over a large area" },
];
