
set ANTHROPIC_BASE_URL=https://agentrouter.org/

set ANTHROPIC_AUTH_TOKEN=sk-08anpalTMTUbeYjVsVbLD3U3xDWiWYeSERwROFER9dCsuLOL
set ANTHROPIC_API_KEY=sk-08anpalTMTUbeYjVsVbLD3U3xDWiWYeSERwROFER9dCsuLOL

set ANTHROPIC_MODEL=claude-opus-4.6