@echo on

set ANTHROPIC_BASE_URL=https://agentrouter.org/

set ANTHROPIC_AUTH_TOKEN=sk-08anpalTMTUbeYjVsVbLD3U3xDWiWYeSERwROFER9dCsuLOL
set ANTHROPIC_API_KEY=sk-08anpalTMTUbeYjVsVbLD3U3xDWiWYeSERwROFER9dCsuLOL

set ANTHROPIC_MODEL=claude-haiku-4-5-20251001